"""
Server-Sent Events endpoint for autonomous world events.

the frontend subscribes to this endpoint and receives
autonomous world events generated by Celery tasks in real-time.

The Celery worker publishes events to Redis pub/sub channel "events:{session_id}".
This endpoint subscribes and forwards them to the browser as SSE.

Endpoint:
  GET /events/world/{session_id}  — SSE stream of autonomous world events
"""

from __future__ import annotations

import asyncio
import json
import logging

import redis.asyncio as aioredis
from fastapi import APIRouter, Request
from fastapi.responses import StreamingResponse

from config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()

router = APIRouter(prefix="/events", tags=["events"])


async def _world_event_stream(session_id: str, request: Request):
    """
    Subscribe to Redis pub/sub and yield SSE events as they arrive.

    Yields:
        SSE-formatted lines: "data: {json}\n\n"
        Heartbeat: ": ping\n\n"  (every 15 seconds to keep connection alive)
    """
    redis: aioredis.Redis | None = None
    pubsub = None

    try:
        redis = await aioredis.from_url(
            settings.redis_url,
            encoding="utf-8",
            decode_responses=True,
        )
        pubsub = redis.pubsub()
        await pubsub.subscribe(f"events:{session_id}")
        logger.info("SSE client subscribed to events:%s", session_id)

        # Send an immediate connect confirmation
        yield f"data: {json.dumps({'type': 'connected', 'session_id': session_id})}\n\n"

        heartbeat_interval = 15  # seconds
        elapsed = 0
        check_interval = 0.5  # poll every 500ms

        while True:
            # Check if client disconnected
            if await request.is_disconnected():
                logger.info("SSE client disconnected from events:%s", session_id)
                break

            message = await pubsub.get_message(ignore_subscribe_messages=True, timeout=check_interval)

            if message and message["type"] == "message":
                data = message["data"]
                yield f"data: {data}\n\n"
                elapsed = 0  # reset heartbeat timer

            elapsed += check_interval
            if elapsed >= heartbeat_interval:
                yield ": ping\n\n"
                elapsed = 0

            await asyncio.sleep(0)  # yield control

    except asyncio.CancelledError:
        pass
    except Exception as exc:
        logger.error("SSE world events error for session %s: %s", session_id, exc)
        yield f"data: {json.dumps({'type': 'error', 'message': str(exc)})}\n\n"
    finally:
        if pubsub:
            try:
                await pubsub.unsubscribe(f"events:{session_id}")
                await pubsub.aclose()
            except Exception:
                pass
        if redis:
            try:
                await redis.aclose()
            except Exception:
                pass
        logger.info("SSE stream closed for events:%s", session_id)


@router.get("/world/{session_id}")
async def stream_world_events(session_id: str, request: Request):
    """
    Subscribe to real-time autonomous world events for a session.

    Returns a Server-Sent Events stream. The frontend connects once and
    receives events as the Celery workers generate them.

    Each event has the shape:
      {"type": "world_event", "text": "Bandits have raided the north gate..."}

    Usage in frontend:
      const evtSrc = new EventSource(`/api/v1/events/world/${sessionId}`)
      evtSrc.onmessage = (e) => { const data = JSON.parse(e.data); ... }
    """
    return StreamingResponse(
        _world_event_stream(session_id, request),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
            "Access-Control-Allow-Origin": "*",
        },
    )
